### ISSUE TITLE
After restarting the storage wipes out :(

### ISSUE THREAD

**Issue by pritasam** [raphaelpor/sync-storage#3]
Hi after restarting I dont get the saved values

**Comment by raphaelpor** [comment]
Hello!

What device are you using to test?
Could you also paste your code here?

**Comment by OleksiiLyhun** [comment]
Hello!

I have the same problem, I run the app on Android Studio on Nexus 6

**Comment by raphaelpor** [comment]
Thanks @OleksiiLyhun!
It seems to be this issue: https://github.com/facebook/react-native/issues/7605.

For now, I think you need to use a real device.

Regards,

**Comment by raphaelpor** [comment]
Hello @wdayanand!
Could you try to use `AsyncStorage.setItem` and `AsyncStorage.getItem` to see what happens?

**Comment by Thomasn57** [comment]
Hello, I've got the same issue on my app. After every restart of the app, datas are gone. Is there any solution for this?

**Comment by olfek** [comment]
PR #4 fixes this issue. The storage wasn't being wiped, this module simply wasn't loading the stored data after a restart due to a context error. (@raphaelpor)

**Comment by raphaelpor** [comment]
Thanks @olfek!
Closing here.

**Comment by ariesbrylle-bms** [comment]
Have the same problem on this version: "sync-storage": "^0.4.2",
