### ISSUE TITLE
how to clear all the stored data

### ISSUE THREAD

**Issue by bbeckk** [raphaelpor/sync-storage#9]
Is there any SyncStorage.removeAll() functionality? How to clear all that are stored?

**Comment by raphaelpor** [comment]
Hello @bbeckk!

You can call `AsyncStorage.clear()` directly.
Documentation: https://facebook.github.io/react-native/docs/asyncstorage#clear

**Comment by wscotten** [comment]
@raphaelpor But how does that clear the data currently stored in the sync-storage cache?

**Comment by demirhancosku** [comment]
> @raphaelpor But how does that clear the data currently stored in the sync-storage cache?

You can use like;
`SyncStorage.getAllKeys().map(k => SyncStorage.remove(k));`

**Comment by raphaelpor** [comment]
Thanks @demirhancosku,

I'm closing this issue for now. :)
